language: ruby
rvm:
- 2.3.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: travis encrypt 'GIT_NAME="ArchGalileu" GIT_EMAIL="geral@gasparsantos.eu" GH_TOKEN=9ceb7ed862b8bf4603a89c2e13b6d425ba061f90'
