backend:
  name: github
  repo: ArchGalileu/biodanza # Path to your Github repository
  branch: master # Branch to update
publish_mode: editorial_workflow
media_folder: "images" # Media files will be stored in the repo under images/uploads
